### ISSUE TITLE
fatal error: hdf5.h: No such file or directory, change from R devel r83603 to r83630

### ISSUE THREAD

**Issue by bbimber** [hhoeflin/hdf5r#199] opened 2023-01-19 14:09 UTC
Hello - 

We have an automated build that runs on github actions, based on the following, which is failing:

version  R Under development (unstable) (2023-01-17 r83630)
os       Ubuntu 20.04.5 LTS
system   x86_64, linux-gnu

This has been running identically to this for some time without errors. It builds against r-devel, which is the only variable I can see here. The last successful build used:

R Under development (unstable) (2023-01-17 r83603)

and this built hdf5r without errors.  The system used: apt to install libhdf5-dev which is version: libhdf5-dev (1.10.4+repack-11ubuntu1). I cannot see any software versions changed based the R version.  This is the error:

```
2023-01-19T00:55:30.8623359Z trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/latest/src/contrib/hdf5r_1.3.7.tar.gz'
2023-01-19T00:55:31.8914172Z Content type 'binary/octet-stream' length 2220296 bytes (2.1 MB)
2023-01-19T00:55:31.9184215Z ==================================================
2023-01-19T00:55:31.9187121Z downloaded 2.1 MB
2023-01-19T00:55:31.9189555Z 
2023-01-19T00:55:32.2955964Z 'getOption("repos")' replaces Bioconductor standard repositories, see
2023-01-19T00:55:32.2957063Z '?repositories' for details
2023-01-19T00:55:32.2957715Z 
2023-01-19T00:55:32.2959468Z replacement repositories:
2023-01-19T00:55:32.2960360Z     CRAN: https://cloud.r-project.org
2023-01-19T00:55:32.2961465Z 
2023-01-19T00:55:33.4921554Z * installing *source* package ‘hdf5r’ ...
2023-01-19T00:55:33.5448436Z ** package ‘hdf5r’ successfully unpacked and MD5 sums checked
2023-01-19T00:55:33.5449831Z ** using staged installation
2023-01-19T00:55:33.9742642Z checking for a sed that does not truncate output... /usr/bin/sed
2023-01-19T00:55:33.9762997Z checking for gawk... gawk
2023-01-19T00:55:33.9811444Z checking for grep that handles long lines and -e... /usr/bin/grep
2023-01-19T00:55:33.9815056Z checking for gcc... gcc
2023-01-19T00:55:34.0860542Z checking whether the C compiler works... yes
2023-01-19T00:55:34.0861403Z checking for C compiler default output file name... a.out
2023-01-19T00:55:34.1368493Z checking for suffix of executables... 
2023-01-19T00:55:34.1980784Z checking whether we are cross compiling... no
2023-01-19T00:55:34.2309712Z checking for suffix of object files... o
2023-01-19T00:55:34.2633445Z checking whether the compiler supports GNU C... yes
2023-01-19T00:55:34.3092434Z checking whether gcc accepts -g... yes
2023-01-19T00:55:34.3792720Z checking for gcc option to enable C11 features... none needed
2023-01-19T00:55:34.4081119Z checking for stdio.h... yes
2023-01-19T00:55:34.4468260Z checking for stdlib.h... yes
2023-01-19T00:55:34.4866308Z checking for string.h... yes
2023-01-19T00:55:34.5265956Z checking for inttypes.h... yes
2023-01-19T00:55:34.5666556Z checking for stdint.h... yes
2023-01-19T00:55:34.6077091Z checking for strings.h... yes
2023-01-19T00:55:34.6481030Z checking for sys/stat.h... yes
2023-01-19T00:55:34.6911015Z checking for sys/types.h... yes
2023-01-19T00:55:34.7369798Z checking for unistd.h... yes
2023-01-19T00:55:34.7389324Z checking for h5cc... /usr/bin/h5cc
2023-01-19T00:55:34.8111192Z checking for HDF5 libraries... yes (version 1.10.4)
2023-01-19T00:55:34.8719013Z checking for hdf5.h... yes
2023-01-19T00:55:34.9598480Z checking for H5Fcreate in -lhdf5... yes
2023-01-19T00:55:35.0071629Z checking for hdf5_hl.h... yes
2023-01-19T00:55:35.1018927Z checking for H5LTpath_valid in -lhdf5_hl... yes
2023-01-19T00:55:35.1666027Z checking for main in -lhdf5_hl... yes
2023-01-19T00:55:35.1699963Z checking for matching HDF5 Fortran wrapper... /usr/bin/h5fc
2023-01-19T00:55:35.1915880Z Found hdf5 with version: 1.10.4
2023-01-19T00:55:35.3099245Z checking for ggrep... /usr/bin/grep
2023-01-19T00:55:35.3127127Z checking whether /usr/bin/grep accepts -o... yes
2023-01-19T00:55:35.3518509Z configure: creating ./config.status
2023-01-19T00:55:35.4556479Z config.status: creating src/Makevars
2023-01-19T00:55:35.5231262Z ** libs
2023-01-19T00:55:35.5389665Z using C compiler: ‘gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0’
2023-01-19T00:55:35.5418049Z cp 1_10_3/*.c 1_10_3/*.h .
2023-01-19T00:55:35.5497727Z if [ "" != "" ]; then patch -p2 < patch_; fi
2023-01-19T00:55:35.5524823Z gcc -I"/opt/R/devel/lib/R/include" -DNDEBUG   -I/usr/local/include   -D__USE_MINGW_ANSI_STDIO  -fpic  -g -O2  -c const_export.c -o const_export.o
2023-01-19T00:55:35.5637670Z In file included from const_export.h:22,
2023-01-19T00:55:35.5638114Z                  from const_export.c:23:
2023-01-19T00:55:35.5639269Z global.h:23:10: fatal error: hdf5.h: No such file or directory
2023-01-19T00:55:35.5639644Z    23 | #include <hdf5.h>
2023-01-19T00:55:35.5639942Z       |          ^~~~~~~~
2023-01-19T00:55:35.5640237Z compilation terminated.
2023-01-19T00:55:35.5654143Z make: *** [/opt/R/devel/lib/R/etc/Makeconf:191: const_export.o] Error 1
2023-01-19T00:55:35.5674107Z ERROR: compilation failed for package ‘hdf5r’
```

The log claims "checking for hdf5.h... yes", but then says it isnt found. When this command is run on the image using R r83603, the gcc command has more -I includes, which I assume is why it works:

```
gcc -I"/opt/R/devel/lib/R/include" -DNDEBUG -I/usr/include/hdf5/serial   -I/usr/local/include   -D__USE_MINGW_ANSI_STDIO  -fpic  -g -O2  -c const_export.c -o const_export.o
```

Is there any reason the R version or anything else would change the ability of hdr5r to resolve hdf5.h? Can you suggest any debugging steps?

**Comment by hhoeflin** [comment] 2023-01-20 04:56
Thanks for reporting this issue. I have reproduced it on my side and am looking into it.

**Comment by adRn-s** [comment] 2023-01-20 12:32
I had the same issue, and 'fixed' (actually, skipped) it by creating a new empty conda environment with package `r-hdf5r` (from either conda-forge or bioconda channel). This one comes pre-compiled and with all dynamic links in place already. So, it works.

Another 'solution'  I was trying was copying over files from `/usr/include/hdf5/serial/*` to /path/to/conda/include/` but I still got a compilation error, though it was downstream, while dynamic linking. Anyway..  I am only telling this, because it might be worth to ask ourselves, Are we facing this issue while having our 'base' conda environment active?

PS. [here](https://stackoverflow.com/a/54373693)'s a plausible solution.

**Comment by hhoeflin** [comment] 2023-01-21 15:58
In the newest updates this error should be fixed. It was a misconfiguration in configure.ac that was triggered by recent versions of R-devel adding additional environment variables for the compilation.

**Closed by hhoeflin** 2023-01-21 15:59 UTC
